apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic-green
  template:
    metadata:
      labels:
        app: petclinic-green
    spec:
      containers:
      - name: petclinic
        image: hbayraktar/petclinic:green
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/petclinic
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
